apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jvmacedos/back:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "mongodb-service:27017/carrosdb"
