apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 32001
  selector:
    app: mongo-express
  type: NodePort
